<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>4ecddccc-948a-44af-899f-a7e7370a991a</UserSecretsId>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MudBlazor" Version="9.7.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="EPPlus" Version="8.6.3" />
		<PackageReference Include="Extensions.MudBlazor.StaticInput" Version="4.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Riok.Mapperly" Version="5.0.0-next.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Home.Budget.Application\Yugen.Home.Budget.Application.csproj" />
		<ProjectReference Include="..\Yugen.Home.Budget.Client\Yugen.Home.Budget.Client.csproj" />
		<ProjectReference Include="..\Yugen.Common.Blazor.Account\Yugen.Common.Blazor.Account.csproj" />
		<ProjectReference Include="..\Yugen.Common.Blazor\Yugen.Common.Blazor.csproj" />
	</ItemGroup>

</Project>
