<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>	
		<PackageReference Include="Blazorise" Version="1.7.*" />
		<PackageReference Include="Blazorise.Bootstrap5" Version="1.7.*" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.*" />
		<PackageReference Include="Blazorise.DataGrid" Version="1.7.*" />
		<PackageReference Include="EPPlus" Version="8.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.HomeBudget.Application\Yugen.HomeBudget.Application.csproj" />
		<ProjectReference Include="..\Yugen.HomeBudget.Client\Yugen.HomeBudget.Client.csproj" />
		<ProjectReference Include="..\Yugen.HomeBudget.Shared\Yugen.HomeBudget.Shared.csproj" />
	</ItemGroup>

</Project>
