<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.4">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yugen.HomeBudget.Application\Yugen.HomeBudget.Application.csproj" />
    <ProjectReference Include="..\Yugen.HomeBudget.Client\Yugen.HomeBudget.Client.csproj" />
    <ProjectReference Include="..\Yugen.HomeBudget.Shared\Yugen.HomeBudget.Shared.csproj" />
  </ItemGroup>


</Project>
