<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Configurations>Release;Debug.Prd;Debug.Dev</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yugen.Home.Budget.Data\Yugen.Home.Budget.Data.csproj" />
  </ItemGroup>

</Project>
