on:
  workflow_dispatch:

name: Run Azure Login With a Service Principal Secret

env:
  AZURE_WEBAPP_NAME: yugen-homebudget-app    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE: 'myapp'              # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                    # set this to the .NET Core version to use
  CLIENT_PROJECT_NAME: Yugen.HomeBudget.Client
  SERVER_PROJECT_NAME: Yugen.HomeBudget.Server
  DATA_PROJECT_NAME: Yugen.HomeBudget.Data
  EF_BUNDLE: 'efbundle'
  SERVER_NAME: 'yugen-homebudget-sql-server.database.windows.net,1433'
  DATABASE: 'yugen-homebudget-sql-db-free'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ${{ env.SERVER_PROJECT_NAME }} --configuration Release

      - name: Install EF Tool
        run: dotnet tool install --global dotnet-ef
            
      - name: Generate EF migration script
        run: dotnet ef migrations bundle --startup-project ${{ env.SERVER_PROJECT_NAME }} --project ${{ env.DATA_PROJECT_NAME }} --self-contained --verbose

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EF_BUNDLE }}
          path: ${{ env.EF_BUNDLE }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'PROD'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.EF_BUNDLE }}
          path: ${{ env.EF_BUNDLE }}

      - name: chmod
        run: sudo chmod +x ./${{ env.EF_BUNDLE }}/${{ env.EF_BUNDLE }}

      - name: ls
        run: ls -al ${{ env.EF_BUNDLE }}

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:          
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      # - name: Azure PowerShell script
      #   uses: azure/powershell@v2
      #   with:          
      #     azPSVersion: "latest"
      #     inlineScript: |
      #       Get-AzWebApp

      # - name: Apply EF migration script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: >            
      #       ./${{ env.EF_BUNDLE }}/${{ env.EF_BUNDLE }} 
      #       --connection 'Server=tcp:${{ env.SERVER_NAME }};Database=${{ env.DATABASE }};Encrypt=True;Authentication=Active Directory Managed Identity;'
      #       --verbose

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:          
          azPSVersion: "latest"
          inlineScript: >            
            ./${{ env.EF_BUNDLE }}/${{ env.EF_BUNDLE }} 
            --connection 'Server=tcp:${{ env.SERVER_NAME }};Database=${{ env.DATABASE }};Encrypt=True;Authentication=Active Directory Managed Identity;'
            --verbose
            
