name: PRD Build and deploy Azure Web App

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_web_app:
    uses: "./.github/workflows/build-web-app.yml"
    secrets: inherit
    with:
      server_project_name: Yugen.HomeBudget.Server

  deploy_web_app:
    uses: "./.github/workflows/deploy-web-app.yml"
    needs: [build_web_app]
    secrets: inherit
    with:
      environment_name: "PRD"
      azure_webapp_name: webapp-yugen-home-budget

  build_ef:
    uses: "./.github/workflows/build-ef.yml"
    secrets: inherit
    with:
      data_project_name: Yugen.HomeBudget.Data
      server_project_name: Yugen.HomeBudget.Server
      # major_minor_patch: ${{needs.build_web_app.outputs.major_minor_patch}}

  deploy_ef:
    uses: "./.github/workflows/deploy-ef.yml"
    needs: [build_ef]
    secrets: inherit
    with:
      environment_name: "PRD"
      server_name: "yugen-homebudget-sql-server.database.windows.net,1433"
      database: "yugen-homebudget-sql-db"
