on:
  workflow_call:
    inputs:
      data_project_name:
        required: true
        type: string
      server_project_name:
        required: true
        type: string

jobs:
  setup_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/setup.yml@main

  build_web_app_stage:    
    uses: yugen-apps/yugen-templates/.github/workflows/build-dotnet-publish.yml@main
    needs: [ setup_stage ]
    with:
      project_name: "${{ inputs.server_project_name }}"
      project_version: "${{ needs.setup_stage.outputs.major_minor_patch }}"

  deploy_web_app_dev_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/deploy-azure-web-app.yml@main
    needs: [ build_web_app_stage ]
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
      google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    with:
      artifact_name: "${{ inputs.server_project_name }}"
      azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME_DEV }}
      environment_name: "DEV"
      db_name: ${{ vars.DB_NAME_DEV }}
      db_server_name: ${{ vars.DB_SERVER_NAME }}

  deploy_web_app_prd_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/deploy-azure-web-app.yml@main
    needs: [ build_web_app_stage ]
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
      google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    with:
      artifact_name: "${{ inputs.server_project_name }}"
      azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME_PRD }}
      environment_name: "PRD"
      db_name: ${{ vars.DB_NAME_PRD }}
      db_server_name: "${{ vars.DB_SERVER_NAME }}"

  build_ef_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/build-dotnet-ef.yml@main
    needs: [ setup_stage ]
    with:
      project_data_name: ${{ inputs.data_project_name }}
      project_startup_name: ${{ inputs.server_project_name }}
      project_version: "${{ needs.setup_stage.outputs.major_minor_patch }}"

  deploy_ef_dev_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/deploy-azure-ef.yml@main
    needs: [ build_ef_stage ]
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      environment_name: "DEV"
      db_name: ${{ vars.DB_NAME_DEV }}
      db_server_name: "${{ vars.DB_SERVER_NAME }}"

  deploy_ef_prd_stage:
    uses: yugen-apps/yugen-templates/.github/workflows/deploy-azure-ef.yml@main
    needs: [ build_ef_stage ]
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      environment_name: "PRD"
      db_name: ${{ vars.DB_NAME_PRD }}
      db_server_name: "${{ vars.DB_SERVER_NAME }}"
