on:
  workflow_call:
    inputs:
      azure_webapp_name:
        required: true
        type: string
      data_project_name:
        required: true
        type: string
      database:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      server_name:
        required: true
        type: string
      server_project_name:
        required: true
        type: string
      user_id:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
        default: "10.0.x"
      ef_version:
        required: true
        type: string
        default: "10.0.*"
        

jobs:
  build_web_app:
    uses: "./.github/workflows/build-web-app.yml"
    secrets: inherit
    with:
      server_project_name: ${{ inputs.server_project_name }}
      dotnet_version: ${{ inputs.dotnet_version }}

  deploy_web_app:
    uses: "./.github/workflows/deploy-web-app.yml"
    needs: [build_web_app]
    secrets: inherit
    with:
      environment_name: ${{ inputs.environment_name }}
      azure_webapp_name: ${{ inputs.azure_webapp_name }}
      server_name: ${{ inputs.server_name }}
      database: ${{ inputs.database }}
      user_id: ${{ inputs.user_id }}

  build_ef:
    uses: "./.github/workflows/build-ef.yml"
    secrets: inherit
    with:
      data_project_name: ${{ inputs.data_project_name }}
      server_project_name: ${{ inputs.server_project_name }}
      dotnet_version: ${{ inputs.dotnet_version }}
      ef_version: ${{ inputs.ef_version }}
      # major_minor_patch: ${{needs.build_web_app.outputs.major_minor_patch}}

  deploy_ef:
    uses: "./.github/workflows/deploy-ef.yml"
    needs: [build_ef]
    secrets: inherit
    with:
      environment_name: ${{ inputs.environment_name }}
      server_name: ${{ inputs.server_name }}
      database: ${{ inputs.database }}
      # user_id: ${{ inputs.user_id }}
