on:
  workflow_call:
    inputs:
      data_project_name:
        required: true
        type: string
      server_project_name:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      ef_version:
        required: true
        type: string
    outputs:
      major_minor_patch:
        value: ${{ jobs.build.outputs.major_minor_patch }}

jobs:
  build_ef:
    runs-on: ubuntu-latest
    env:
      EF_BUNDLE: "efbundle"

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install EF Tool
        shell: bash
        run: >
          dotnet tool install dotnet-ef 
          --global 
          --version ${{ inputs.ef_version }}

      - name: Build with dotnet
        shell: bash
        run: >
          dotnet build ${{ inputs.server_project_name }} 
          --configuration Release 

      - name: Generate EF migration script
        shell: bash
        run: >
          dotnet ef migrations bundle 
          --configuration Release 
          --startup-project ${{ inputs.server_project_name }} 
          --project ${{ inputs.data_project_name }} 
          --self-contained 
          --verbose

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: appsettings
      #     path: ${{ inputs.server_project_name }}/appsettings.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.EF_BUNDLE }}
          path: ${{ env.EF_BUNDLE }}
