on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      server_name:
        required: true
        type: string
      database:
        required: true
        type: string

jobs:
  deploy_new:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }} 

    steps:
      - name: Download efbundle artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.EF_BUNDLE }}
          path: ${{ env.EF_BUNDLE }}

      - name: chmod
        shell: bash
        run: sudo chmod +x ./${{ env.EF_BUNDLE }}/${{ env.EF_BUNDLE }}

      - name: ls
        shell: bash
        run: ls -al ${{ env.EF_BUNDLE }}

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Apply EF migration script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: >
            ./${{ env.EF_BUNDLE }}/${{ env.EF_BUNDLE }}
            --connection 'Server=tcp:${{ inputs.server_name }};Database=${{ inputs.database }};Encrypt=True;Authentication=Active Directory Managed Identity;'
            --verbose