name: yugen-home-budget-cicd

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    uses: "./.github/workflows/build-and-deploy.yml"
    secrets: inherit
    with:
      data_project_name: "Yugen.Home.Budget.Data"
      server_project_name: "Yugen.Home.Budget.Server"
